### ISSUE TITLE
Build error in Windows

### ISSUE THREAD

**Issue by Kerkil** [geggo/gpyfft#12]
I see this error when I run python setup.py install. Looks like it cannot locate MS Visual Studio 2013 installed in the machine asking to install an older version. Is this necessary although I have already MS VS 2013 installed?

C:\Users\butterfly\Documents\GitHub\gpyfft>python setup.py install
copied clFFT.dll, StatTimer.dll
running install
running bdist_egg
running egg_info
writing Gpyfft.egg-info\PKG-INFO
writing top-level names to Gpyfft.egg-info\top_level.txt
writing dependency_links to Gpyfft.egg-info\dependency_links.txt
reading manifest file 'Gpyfft.egg-info\SOURCES.txt'
writing manifest file 'Gpyfft.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying gpyfft\clFFT.dll -> build\lib.win-amd64-2.7\gpyfft
copying gpyfft\StatTimer.dll -> build\lib.win-amd64-2.7\gpyfft
running build_ext
building 'gpyfft.gpyfftlib' extension
error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get
it from http://aka.ms/vcpython27

**Comment by Kerkil** [comment]
I worked around the problem by install VC for Python27 as recommended in the error log. However, now I see a different error. Could anyone please help me fix this? I built clFFT with VS2013 community version. 

C:\Users\butterfly\Documents\GitHub\gpyfft>python setup.py install
copied clFFT.dll, StatTimer.dll
running install
running bdist_egg
running egg_info
writing Gpyfft.egg-info\PKG-INFO
writing top-level names to Gpyfft.egg-info\top_level.txt
writing dependency_links to Gpyfft.egg-info\dependency_links.txt
reading manifest file 'Gpyfft.egg-info\SOURCES.txt'
writing manifest file 'Gpyfft.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying gpyfft\clFFT.dll -> build\lib.win-amd64-2.7\gpyfft
copying gpyfft\StatTimer.dll -> build\lib.win-amd64-2.7\gpyfft
running build_ext
building 'gpyfft.gpyfftlib' extension
C:\Users\butterfly\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python
\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\butterf
ly\Documents\GitHub\clFFT\src\include -IC:\Users\butterfly\Documents\GitHub\clFF
T\build\include -IC:\Intel\INDE\code_builder_5.1.0.25\include -IC:\Python27\incl
ude -IC:\Python27\PC /Tcgpyfft\gpyfftlib.c /Fobuild\temp.win-amd64-2.7\Release\g
pyfft\gpyfftlib.obj
gpyfftlib.c
gpyfft\gpyfftlib.c(4916) : warning C4244: '=' : conversion from 'Py_ssize_t' to
'int', possible loss of data
gpyfft\gpyfftlib.c(6155) : warning C4244: 'function' : conversion from 'Py_ssize
_t' to 'cl_uint', possible loss of data
C:\Users\butterfly\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python
\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\butter
fly\Documents\GitHub\clFFT\build\staging\Debug /LIBPATH:C:\Python27\libs /LIBPAT
H:C:\Python27\PCbuild\amd64 clFFT.lib /EXPORT:initgpyfftlib build\temp.win-amd64
-2.7\Release\gpyfft\gpyfftlib.obj /OUT:build\lib.win-amd64-2.7\gpyfft\gpyfftlib.
pyd /IMPLIB:build\temp.win-amd64-2.7\Release\gpyfft\gpyfftlib.lib /MANIFESTFILE:
build\temp.win-amd64-2.7\Release\gpyfft\gpyfftlib.pyd.manifest
LINK : fatal error LNK1181: cannot open input file 'clFFT.lib'
error: command 'C:\\Users\\butterfly\\AppData\\Local\\Programs\\Common\\Microsof
t\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status

**Comment by Kerkil** [comment]
I figured that VC2013 distributed all the library files in various locations. By adding the paths, I was able to build gpyfft finally.

**Comment by geggo** [comment]
Good that you could figure out by yourself the issues you had. Could you please provide some more detailed information on how you succeeded to build clFFT and gpyfft, it might be interesting for other users.

Gregor
