### ISSUE TITLE
can't find libclFFT.so.2

### ISSUE THREAD

**Issue by ZacDiggum** [geggo/gpyfft#13]
Hi there,

I'm on Linux Mint 17.2 with fglrx as OpenCL platform. I installed gpyfft using prebuilt binaries from https://github.com/clMathLibraries/clFFT/releases. Gpyfft wouldn't find libclFFT.so.2. So I created a file called libclFFT.so.2.conf in ld.so.conf.d with the proper path to libclFFT.so.2. That did the trick when installing pyopencl_blas. Still won't work...
Anyone willing to help a newbie?

**Comment by geggo** [comment]
> Am 09.07.2015 um 16:26 schrieb ZacDiggum <notifications@github.com>:
> 
> Hi there,
> 
> I'm on Linux Mint 17.2 with fglrx as OpenCL platform. I installed gpyfft using prebuilt binaries from https://github.com/clMathLibraries/clFFT/releases <https://github.com/clMathLibraries/clFFT/releases>. Gpyfft wouldn't find libclFFT.so.2. So I created a file called libclFFT.so.2.conf in ld.so.conf.d with the proper path to libclFFT.so.2. That did the trick when installing pyopencl_blas. Still won't work...
> Anyone willing to help a newbie?
> 
> 

Have no idea about the intricacies of path handling, just 2 observations:
* gpyfft links to libclFFT.so, so perhaps just a symbolic link is missing?
* when building for Windows, clFFT.dll is copied into the module directory of gpyfft to avoid fiddling with PATH, you could (manually) do the same

Gregor

**Comment by ZacDiggum** [comment]
Hi, thanks for your help. I just put the library in /usr/local/lib. Not very elegant, but it works. BTW, gpyfft gives me a speedup of about one third over Reikna, when operating on large arrays (like 4k x 4k).
I'll close the issue.

**Comment by yves-surrel** [comment]
Hi

Same problem here on Ubuntu 20.04

Compiled successfully clFFT and got libclFFT.so.2 in /usr/local/lib64, which is the directory indicated in setup.py under the section 'linux':

```
CLFFT_LIB_DIRS = [r'/usr/local/lib64']
```

Ran `python setup.py build` and `python setup.py install` in gpyfft master directory (with no error apparently), and `import gpyfft` in python complains about not finding licclFFT.so.2.

Any idea? Why the line `CLFFT_LIB_DIRS = [r'/usr/local/lib64']`is not taken into account ?

**Comment by yves-surrel** [comment]
Also tried to copy the clFFT lib in the ..../site-packages/gpyfft directory, along with gpyfftlib.cpython-38-x86_64-linux-gnu.so, without success.

**Comment by geggo** [comment]
I also encountered this kind of problem. By default, clFFT gets installed to /usr/local/lib64. But, this location is not contained in the library search path on ubuntu, which expects it to be in /usr/local/lib/x86_64-linux-gnu. You can just manually copy the clFFT libs to this location.

Another option is to permanently add /usr/local/lib64 to the library search path:

`echo "/usr/local/lib64" > usr_local_lib64.conf`
`sudo mv usr_local_lib64.conf /etc/ld.so.conf.d`
`sudo ldconfig`
