### ISSUE TITLE
starting a QtGui app kills gpyfft

### ISSUE THREAD

**Issue by dboonz** [geggo/gpyfft#15]
Thanks for the repository! In general it works great. I just found out one weird issue, though. If I create a transform plan after I created a QT application (it does not matter wether you take pyside of pyqt4), gpyfft fails with a horrible message. Please see the minimal working example below. Do you have any idea how to fix this?

## Code

    # from PyQt4 import QtGui
    from PySide import QtGui  # it does not matter which backend we choose
    import sys
    import numpy as np
    import gpyfft
    import pyopencl.array as cl_array
    import pyopencl as cl

    ctx = cl.create_some_context(interactive=False)
    queue = cl.CommandQueue(ctx)

    # numpy data
    np_data = np.random.rand(64, 64)
    gpu_data = cl_array.to_device(queue, np_data)

    print "Initializing transform before creating QT app"
    transform = gpyfft.fft.FFT(ctx, queue, [gpu_data])

    # creating a QT gui application
    app = QtGui.QApplication(sys.argv)

    print "Initializing the same transform after creating QT app"
    np_data = np.random.rand(64, 64)
    gpu_data = cl_array.to_device(queue, np_data)
    transform = gpyfft.fft.FFT(ctx, queue, [gpu_data])
    print "Successful"

    print "Initializing a new with a different shape after creating QT app"
    np_data = np.random.rand(64, 128)
    gpu_data = cl_array.to_device(queue, np_data)
    transform = gpyfft.fft.FFT(ctx, queue, [gpu_data])  # FAILS

### last part of the error message:

            ^
    <kernel>:80:47: error: invalid digit 'f' in decimal constant
    (float2)(-0,9807852804032304305792422383092344f,     -0,1950903220161286089062713244857150f),
                                              ^
    <kernel>:81:47: error: invalid digit 'f' in decimal constant
    (float2)(-0,2902846772544632747425907837168779f, 0,9569403357322086023373231000732630f),
                                              ^
    <kernel>:541:8: warning: assigning to '__global float2     *__attribute__((address_space(16776963)))' from 'const __global float2 *' discards qualifiers
        lwbIn = gbIn + iOffset;
              ^ ~~~~~~~~~~~~~~
    <kernel>:570:8: warning: assigning to '__global float2  *__attribute__((address_space(16776963)))' from 'const __global float2 *' discards qualifiers
        lwbIn = gbIn + iOffset;
              ^ ~~~~~~~~~~~~~~

    ************************************************
    Traceback (most recent call last):
       File "minimal_error.py", line 32, in <module>
     transform = gpyfft.fft.FFT(ctx, queue, [gpu_data])  # FAILS
     File "/home/dbs660/research_subjects/fresnel_imaging/dev/gpyfft/gpyfft/fft.py", line 51, in __init__
     plan.bake(self.queue)
     File "gpyfftlib.pyx", line 415, in gpyfft.gpyfftlib.Plan.bake (gpyfft/gpyfftlib.c:5008)
     File "gpyfftlib.pyx", line 47, in gpyfft.gpyfftlib.errcheck (gpyfft/gpyfftlib.c:1522)
     gpyfft.gpyfftlib.GpyFFT_Error: 'BUILD_PROGRAM_FAILURE'

**Comment by geggo** [comment]
> Am 10.11.2015 um 16:04 schrieb Dirk B. <notifications@github.com>:
> 
> Thanks for the repository! In general it works great. I just found out one weird issue, though. If I create a transform plan after I created a QT application (it does not matter wether you take pyside of pyqt4), gpyfft fails with a horrible message. Please see the minimal working example below. Do you have any idea how to fix this?
> 
> Code
> 
> # from PyQt4 import QtGui
> from PySide import QtGui  # it does not matter which backend we choose
> import sys
> import numpy as np
> import gpyfft
> import pyopencl.array as cl_array
> import pyopencl as cl
> 
> ctx = cl.create_some_context(interactive=False)
> queue = cl.CommandQueue(ctx)
> 
> # numpy data
> np_data = np.random.rand(64, 64)
> gpu_data = cl_array.to_device(queue, np_data)
> 
> print "Initializing transform before creating QT app"
> transform = gpyfft.fft.FFT(ctx, queue, [gpu_data])
> 
> # creating a QT gui application
> app = QtGui.QApplication(sys.argv)
> 
> print "Initializing the same transform after creating QT app"
> np_data = np.random.rand(64, 64)
> gpu_data = cl_array.to_device(queue, np_data)
> transform = gpyfft.fft.FFT(ctx, queue, [gpu_data])
> print "Successful"
> 
> print "Initializing a new with a different shape after creating QT app"
> np_data = np.random.rand(64, 128)
> gpu_data = cl_array.to_device(queue, np_data)
> transform = gpyfft.fft.FFT(ctx, queue, [gpu_data])  # FAILS
> last part of the error message:
> 
>         ^
> <kernel>:80:47: error: invalid digit 'f' in decimal constant
> (float2)(-0,9807852804032304305792422383092344f,     -0,1950903220161286089062713244857150f),

Hi Dirk,

interesting feature! It seems that Qt changes the locale settings, and the clFFT library uses the locale settings for printing floats, using , instead of . for the decimal point. Could you try changing the the settings (locale.setlocale(…)) after initializing the Qt app?

Gregor

PS: which OS?

**Comment by dboonz** [comment]
Hi Gregor!

Thanks for the swift reply! Yes, if I add

locale.resetlocale()

the program works, and I don't see anything going wrong with pyQT (but I 
have a very minimal program).

Can we just put that in the code somewhere?

OS: Linux mint
NVIDIA graphics card GTX780
Driver version 352

regards,

Dirk

**Comment by geggo** [comment]
> Am 10.11.2015 um 20:34 schrieb Dirk B. <notifications@github.com>:
> 
> Hi Gregor!
> 
> Thanks for the swift reply! Yes, if I add
> 
> locale.resetlocale()
> 
> the program works, and I don't see anything going wrong with pyQT (but I 
> have a very minimal program).
> 
> Can we just put that in the code somewhere?
> 
> OS: Linux mint
> NVIDIA graphics card GTX780
> Driver version 352
> 
> regards,
> 

Dear Dirk,

I could reproduce the problem on OS X, indeed initializing a Qt app switch the global locale settings, and clFFT does not cope with it. So at least there is a workaround. I think a proper fix is to modify clFFT, forcing it to always use the standard C locale when converting a float to a string, e.g. setting 

s.imbue(std::locale("C“))

for any stringstream used to build the kernel source. But I could not yet locate the right spot. 

Gregor

**Comment by geggo** [comment]
Made a pull request clMathLibraries/clFFT#120 that might fix this issue (which actually is a clFFT issue ;-))

**Comment by dboonz** [comment]
nice! Thanks!

On Wed, Nov 11, 2015 at 6:44 PM, Gregor Thalhammer <notifications@github.com

**Comment by geggo** [comment]
Fixed by PR clMathLibraries/clFFT#120. Closing.
