### ISSUE TITLE
ubuntu install fails on import

### ISSUE THREAD

**Issue by andyofmelbourne** [geggo/gpyfft#18]
I get the following error after installation then import of the gpyfft module: 
`
ImportError: /home/amorgan/.local/lib/python2.7/site-packages/gpyfft-0.2.2-py2.7-linux-x86_64.egg/gpyfft/gpyfftlib.so: undefined symbol: clfftSetPlanCallback
`
## Details:

I am trying to get gpyfft fired up on a gpu cluster for work (running under linux sl6). To this end I am testing at home under Ubuntu with a Haswell HD GPU installing as a 'user' with no root privileges. Anyway:
I downloaded the clFFT prebuilt binaries at /home/amorgan/Physics/2016/pyopencl/clFFT-Full-2.10.0-Linux-x64/
`
$ git clone https://github.com/geggo/gpyfft.git
$ cd gpyfft
$ export LDFLAGS="-L/home/amorgan/Physics/2016/pyopencl/clFFT-Full-2.10.0-Linux-x64/lib64 " 
`
Then I set:
`
CLFFT_DIR = r'/home/amorgan/Physics/2016/pyopencl/clFFT-Full-2.10.0-Linux-x64'
CL_INCL_DIRS = ['/home/amorgan/Physics/2016/pyopencl/clFFT-Full-2.10.0-Linux-x64/include']
`
in setup.py. 
`
$ python setup.py build
`
This works with a single warning:
`
/home/amorgan/Physics/2016/pyopencl/clFFT-Full-2.10.0-Linux-x64/include/clFFT.h:257:2: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  CLFFTAPI clfftStatus clfftTeardown( );
`
Instillation works with no warnings:
`
$ python setup.py install --user
$ cd ~
$ ipython
`

> ## In [1]: import gpyfft
> 
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-4b3d41c00a5a> in <module>()
> ----> 1 import gpyfft
> 
> /home/amorgan/.local/lib/python2.7/site-packages/gpyfft-0.2.2-py2.7-linux->x86_64.egg/gpyfft/**init**.py in <module>()
>        8     raise RuntimeError("Do NOT use gpyfft from its sources: build it and use the built version")
>        9 
> ---> 10 from .gpyfftlib import GpyFFT, GpyFFT_Error, Plan
>       11 from .fft import *
> 
> ImportError: /home/amorgan/.local/lib/python2.7/site-packages/gpyfft-0.2.2-py2.7-linux-x86_64.egg/gpyfft/gpyfftlib.so: undefined symbol: clfftSetPlanCallback

**Comment by geggo** [comment]
> Am 31.01.2016 um 20:49 schrieb andyofmelbourne <notifications@github.com>:
> 
> I get the following error after installation then import of the gpyfft module: 
> 
> ImportError: /home/amorgan/local/lib/python27/site-packages/gpyfft-022-py27-linux-x86_64egg/gpyfft/gpyfftlibso: undefined symbol: clfftSetPlanCallback
> 

clfftSetPlanCallback has been recently added to clFFT, probably the prebuilt binaries you are using haven’t been updated. Building them yourself is not a big issue, then you will also profit from improved performance. Alternatively, checkout an older version of gpyfft.

Gregor
