### ISSUE TITLE
No examples in documentation

### ISSUE THREAD

**Issue by darkstar007** [geggo/gpyfft#22]
I think the documentation could really do with some examples on how to actually use the library and what best practice is.

Thanks,

Matt

**Comment by geggo** [comment]
Agreed, documentation should be improved. To start, I added a basic example, hope that helps.

Gregor

**Comment by darkstar007** [comment]
OK, thanks.

I'm reading some (complex) data from a file and doing a bunch of (1D) FFTs on it, then reading more data from file, more FFTs, and repeat. A lot! So I assume an optimum way is to to create_plan() for each of the 3 or 4 sizes of FFT I will need, then then inside the (read + FFT) loop  just plan.enqueue_transform() as required?

At some point I'll need to be able to do something similar with real data (rather than complex). How do I set up a real-->complex FFT in a plan? (If I just give it a real array, does it just do 'the right thing'?)

Thanks,

Matt

**Comment by geggo** [comment]
Indeed, for each size of an FFT you should set up a plan, and reuse the plans to minimize overheads. Also try to use batched transforms to obtain optimal performance. Memory layout has a big impact, you have to benchmark this. For you using the low-level interface (which also supports real-to-complex transforms) seems more appropriate, have a look at the clFFT docs for the details.

**Comment by darkstar007** [comment]
OK. I'll try and figure out the low-level interface.

**Comment by darkstar007** [comment]
Is there a way to get the enums - i.e. something like gpyfft.CLFFT_HERMITIAN_INTERLEAVED? I've had a grep around and they don't seem to be in there, but are defined in the cython code. 

Anyway, this is my code for doing a simple real==>complex FFT:

```python
#!/usr/bin/env python

import numpy as np

import pyopencl as cl
import pyopencl.array as cla

from gpyfft import GpyFFT_Error
from gpyfft import GpyFFT

from matplotlib import pyplot as plt

import sys

data = np.sin(0.1 * np.arange(2048, dtype=np.float32))

G = GpyFFT(debug=False)
    
context = cl.create_some_context()
queue = cl.CommandQueue(context)

dev_data = cla.zeros(queue, data.shape, np.float32)
dev_fft_data = cla.zeros(queue, (data.shape[0]/2 + 1,), np.complex64)

plan = G.create_plan(context, data.shape)
plan.inplace = False
plan.precision = 1   # Wish I could do gpyfft.CLFFT_SINGLE
plan.scale_forward = 1
plan.layouts = (5,3) # Wish ... (gpyfft.CLFFT_REAL, gpyfft.CLFFT_HERMITIAN_INTERLEAVED)

plan.bake(queue)

dev_data.set(data)

plan.enqueue_transform((queue,),
		       (dev_data.data,),
		       (dev_fft_data.data,))

queue.finish()

cl_fft_data = dev_fft_data.get()

np_fft = np.fft.rfft(data)
plt.subplot(311)
plt.plot(np.abs(cl_fft_data), label='OpenCL')
plt.plot(np.abs(np_fft), label='Numpy')
plt.legend()

plt.subplot(312)
plt.plot(np.abs(cl_fft_data) - np.abs(np_fft), label='Amp Diff')
plt.legend()

plt.subplot(313)
plt.plot(np.angle(cl_fft_data) - np.angle(np_fft), label='Phase Diff')
plt.legend()

plt.show()

```

**Comment by geggo** [comment]
I comitted a small change, now declaring the enums as cpdef instead of cdef, so with recent cython the enums are now visible at the Python level. Now you can access them in your script by

import gpyfft.gpyfftlib
gpyfft.gpyfftlib.CLFFT_REAL

Gregor

**Comment by geggo** [comment]
PS: Great that you tried the real-to-complex transform, I never did. Seems not a big issue to support this also in the high level wrapper ;-)

**Comment by darkstar007** [comment]
Cool. I just did a git pull & re-install and can now pick up the enums - thanks!

Matt

**Comment by geggo** [comment]
just a notice before closing this old issue, in the mean time real to complex transforms are supported by the high-level interface, thanks for the hint how to implement it.
