### ISSUE TITLE
Cython errors in setup.py on Ubuntu

### ISSUE THREAD

**Issue by rajb245** [geggo/gpyfft#31]
I'm on Ubuntu 16.04, with clFFT installed from source.

I modified setup.py in the following way:
    CLFFT_DIR = r'/home/user/clFFT'
    CLFFT_LIB_DIR = r'/usr/local/lib64'
    CLFFT_INCL_DIRS = [os.path.join(CLFFT_DIR, 'src', 'include'), ]
    CL_INCL_DIRS = ['/usr/include/CL']

This is where my libraries and sources and includes and headers are on my system. When setup.py goes to Cythonize the extension, however, the following errors occur:

```
~/gpyfft$ python setup.py install
Compiling gpyfft/gpyfftlib.pyx because it changed.
[1/1] Cythonizing gpyfft/gpyfftlib.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    property precision:
        """the floating point precision of the FFT data"""    
        def __get__(self):
            cdef clfftPrecision precision
            errcheck(clfftGetPlanPrecision(self.plan, &precision))
            return clfftPrecision_(precision)
                                 ^
------------------------------------------------------------

gpyfft/gpyfftlib.pyx:215:34: 'clfftPrecision_' is not a constant, variable or function identifier

Error compiling Cython file:
------------------------------------------------------------
...
    property precision:
        """the floating point precision of the FFT data"""    
        def __get__(self):
            cdef clfftPrecision precision
            errcheck(clfftGetPlanPrecision(self.plan, &precision))
            return clfftPrecision_(precision)
                                 ^
------------------------------------------------------------

gpyfft/gpyfftlib.pyx:215:34: Calling non-function type 'clfftPrecision_'
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    ext_modules=cythonize(extensions),
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: gpyfft/gpyfftlib.pyx

```
I'm not familiar with Cython, but it looks like this is a wrapper to the underlying clFFT functions, where the function names with the underline are perhaps supposed to be loaded from the library? But it seems they are not being loaded and the function names with the underlines are undefined. Any tips for how I can correct this?

**Comment by geggo** [comment]
Hi,
it seems you are using an older version of cython, please upgrade to a more recent one (>= 0.24 should be ok). For this I would recommend using e.g. the anaconda python distribution instead of the Ubuntu system python.

Also, if I remember correctly, on Ubuntu /usr/local/lib64 is *not* part of the default shared library search path, so you have to fiddle with LD_LIBRARY_PATH and ldconfig.

hope that helped
Gregor

**Comment by rajb245** [comment]
Thanks for the tips, I'll try a newer Cython. I suspect a pip install should overwrite or override the Ubuntu packages. You're right about Ubuntu's default ld settings, but the file I added to /etc/ld.so.conf.d/ takes care of that (clFFT examples load the right libraries from that directory and work just fine). If a newer Cython fixes things, I'll let you know tomorrow and hopefully we can mark this as closed.

**Comment by rajb245** [comment]
Yup, installing cython via pip and rerunning things fixed this. Thanks!

**Comment by youssef-snoussi** [comment]
Hello I have the same issue with Cython 0.29.22 on ubunu 18.04, any hints to proceed except upgrading to a newer version

**Comment by geggo** [comment]
Cythonizing with cython 0.29.22 (on MacOS) is ok, so likely you are picking up an older version when building.

**Comment by youssef-snoussi** [comment]
I'm actually not building it myself, I face that problem when I try to install Spacy with pip, the stacktrace is 

 **spacy/kb.pyx:408:28: 'PreshMap' is not a constant, variable or function identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            assert nr_entities == self.get_size_entities()
    
            # STEP 3: load aliases
            cdef int64_t nr_aliases
            reader.read_alias_length(&nr_aliases)
            self._alias_index = PreshMap(nr_aliases+1)**

**Comment by geggo** [comment]
That issue is completely unrelated to gpyfft, closing it.
