### ISSUE TITLE
could you integrate the benchmark in the gpyfft module

### ISSUE THREAD

**Issue by picca** [geggo/gpyfft#38]
It would be really nice to be able to have this

`python -m gpyfft.benchmark`

This should allow peoples to test there implementation of opencl.

this should parse something on the command line in order to select the device and other goodies.

thanks

**Comment by geggo** [comment]
> Am 28.09.2017 um 15:07 schrieb picca <notifications@github.com>:
> 
> It would be really nice to be able to have this
> 
> python -m gpyfft.benchmark
> 
> This should allow peoples to test there implementation of opencl.
> 
> 
Good idea, just moved benchmark.py down into package dir.
> this should parse something on the command line in order to select the device and other goodies.
> 
> 
For the moment just kept it as it is, pull requests welcome ;-)
