### ISSUE TITLE
Installation when clFFT has been installed using conda ?

### ISSUE THREAD

**Issue by sajid-ali-nu** [geggo/gpyfft#39]
I've noticed that the setup file searches for clFFT header files and SDK assuming that the clFFT package was built using cmake from source. 

How would the libraries change when clFFT is installed using conda ?

**Comment by geggo** [comment]
Great joy! There is a conda package for clFFT!

In this case you can give an empty list for CLFFT_LIB_DIRS and CLFFT_INCL_DIRS in setup.py. Building gpyfft in an anaconda environment then picks the headers and libs from .../include and .../lib of your anaconda environment, where the clfft conda package installs its content.

On Windows and Linux you might need to point CL_INCL_DIRS to the OpenCL headers.

I should learn how to create conda recipes...

Gregor

**Comment by sajid-ali-nu** [comment]
There's a folder containing the nvidia.icd file, is that what you mean by OpenCL header or should I install the AMDSDK package ?

**Comment by geggo** [comment]
To build gpyfft you need the OpenCL header files (CL/cl.h, ...)
You could get them from your hardware vendors SDK, your favourite linux distribution package manager, or take the official [OpenCL-Headers](https://github.com/KhronosGroup/OpenCL-Headers)
They should match the version of the OpenCL runtime you are using.

Gregor

**Comment by sajid-ali-nu** [comment]
I did a messy workaround where I inspected the library structure of conda clfft and non-conda clfft and what works is setting the clfft directory as ~/anaconda3/pkgs/clfft-(version) and removing the 'src' string for clfft_incl_dirs. 

I did check the version of opencl by running pyopencl.get_cl_header_version() which was 2.1 with Nvidia gpu as the platform and linked the official header files as you suggested and everything seems to work at the moment. 

Thank You. 

(Just out of curiosity, the above implies that I'm running OpenCL 2.1 on nvidia which is not what should happen according to [1](https://en.wikipedia.org/wiki/OpenCL#OpenCL_2.1_support) )

**Comment by geggo** [comment]
Giving an empty list for CLFFT_INCL_DIRS and CLFFT_LIB_DIRS did not work for you?

pyopencl.get_cl_header_version() returns the version of the header files against which pyopencl has been built. But likely (with Nvidia) your device only supports OpenCL 1.2.

**Comment by sajid-ali-nu** [comment]
I don't remember exactly but i think it was an error to do me giving an empty string instead of an empty list.

**Comment by zachjweiner** [comment]
On this topic, what I find works is
```bash
if 'Linux' in system:
    CLFFT_DIR = os.environ['CONDA_PREFIX']
    CLFFT_LIB_DIR = os.path.join(CLFFT_DIR, 'lib')
    CLFFT_INCL_DIRS = [os.path.join(CLFFT_DIR, 'include')]
    CL_INCL_DIRS = []
```
That is, linking to `clFFT` should work if it was installed with conda. Regarding `CL_INCL_DIRS`, it seems to me `gcc` can find the cl headers in the default paths it looks in (at least, when installed via CUDA). (I have no idea if this would work on Windows or macOS.)

This seems like it would be a good default, as it has a good chance of working out of the box  (whereas the current `setup.py`  absolutely requires modification, which was a bit of a painful process the first time around for me).

@geggo, would you modify `setup.py` as such (or accept a PR, if that would be more convenient)? And thanks for providing these wrappers!

**Comment by geggo** [comment]
Changing the default settings in setup.py to work with conda does not fully resolve the mess of building gpyfft. But a PR adding this to the docs is welcome.
Best approach would be a conda recipe and package to make installation painless.

**Comment by zachjweiner** [comment]
I don't disagree, just figured it might be a better default in the interim.

Actually, a search on github finds [this repo](https://github.com/luc-j-bourhis/gpyfft-conda-recipe) - perhaps inspiration might be drawn from here?

**Comment by geggo** [comment]
A conda package built with the recipe above gives a segfault, tried on OS X. Needs more testing/debugging...

**Comment by zachjweiner** [comment]
Thanks for looking into doing this. Any luck since? Let me know if I can help by testing on the (Linux) clusters and machines I have access to.

**Comment by geggo** [comment]
On OS X building a conda package for gpyfft with clfft (recent github) built manually seems ok, so I guess the clfft conda package is guilty for causing segfaults. Unfortunately, there is no more recent release of clfft, which is in maintenance only mode. 
Did not yet test on Linux, interesting to know if building a conda package there with clfft from conda-forge is ok, did you try?

**Comment by zachjweiner** [comment]
Strange - it seems the latest clfft release is the version on conda-forge.

I have not - I have no experience with conda packageing. Do you expect a linux recipe to be similar to your OS X one (or the one I linked to above)? If so, I can probably find time to give it a shot.
