### ISSUE TITLE
Cannot open include file: 'clFFT.h'

### ISSUE THREAD

**Issue by jacione** [geggo/gpyfft#49]
I'm currently trying to build this package in Windows 10, and getting the following error message:

`gpyfft\gpyfftlib.cpp(642): fatal error C1083: Cannot open include file: 'clFFT.h': No such file or directory`

I've searched the entire clFFT directory but found no files named `clFFT.h`. I built the clFFT package with CMake, and followed the instructions closely, though I didn't include any of the optional dependencies (FFTW, etc). Overall, it looks like the clFFT directory expected by `setup.py` is not the same as the directory that was built on my machine.

As a sidenote, I did make a few minor changes to `setup.py` so that it could find my clFFT `.dll` files and my openCL SDK (Intel instead of AMD). As far as I can tell, that shouldn't have affected this issue, but it might be worth noting just in case.

**Comment by geggo** [comment]
clFFT.h is part of the clFFT source files, see https://github.com/clMathLibraries/clFFT/tree/master/src/include
