### ISSUE TITLE
How to do inverse FFT (in 3D) ?

### ISSUE THREAD

**Issue by ProkopHapala** [geggo/gpyfft#54]
I'm using `gpyfft` and `pyOpenCL`  for calculating poisson equation on GPU.

the algorithm is like this>
  1. FFT charge density $\rho(r)$ to k-space $\rho(k)$
  2. multiply fequncey component by 1/|k^2| krenel, $$V(k)= \rho(k)/|k|^2$$
  3. inverse-FFT the resulting electrostatic potential $V(k)$ -> $V(r)$ 

But I don't know how to initialize inverse fourier transform, so instead I do two forward fourier tranforms. The result is however mirror imaged. It is not a big deal, but still itwould be better to initialize inverse FFT. 

```python

    def prepare_poisson(self, sh=None):
        if sh is None: sh=self.gsh.ns[::-1] 
        print("GridFF_cl::prepare_poisson() sh=", sh )
        self.Qgrid_cla = cl_array.Array(self.queue, shape=sh, dtype=np.complex64, data=self.Qgrid_buff )
        self.Vgrid_cla = cl_array.Array(self.queue, shape=sh, dtype=np.complex64, data=self.Vgrid_buff )
        self.transform         = clu.FFT(self.ctx, self.queue, self.Qgrid_cla, axes=(0, 1, 2))
        self.inverse_transform = clu.FFT(self.ctx, self.queue, self.Vgrid_cla, axes=(0, 1, 2))

    def _poisson(self, sz_glob, sz_loc, ns, coefs_cl ):
        event, = self.transform.enqueue() 
        event.wait()
        self.prg.poissonW( self.queue, sz_glob, sz_loc,       ns, self.Qgrid_buff, self.Vgrid_buff, coefs_cl )
        event, = self.inverse_transform.enqueue()
        event.wait()

    def poisson(self, bReturn=True, sh=None, dV=None ):

        clu.try_load_clFFT()
        if sh is None: sh=self.gsh.ns[::-1] 
        nxyz = np.int32( sh[0]*sh[1]*sh[2] )

        if dV is None: dV = self.gsh.dV

        buff_names={'Qgrid','Vgrid'}
        self.try_make_buffs(buff_names, 0, nxyz)
        self.prepare_poisson( sh=sh )

        ns_cl    = np.array( (*sh[::-1],nxyz), dtype=np.int32 )
        #sc_ewald = 4*np.pi*dV*COULOMB_CONST
        sc_ewald = 4*np.pi*dV*dV*COULOMB_CONST
        coefs_cl = np.array( (0.0,0.0,0.0, sc_ewald ), dtype=np.float32 )

        nL = self.nloc
        nG = clu.roundup_global_size( nxyz, nL)
        self._poisson( (nG,), (nL,), ns_cl, coefs_cl )        

        if bReturn:
            sh_ = (*sh,2)
            print( "sh ", sh_ )
            Vgrid = np.zeros( sh_, dtype=np.float32   )  
            cl.enqueue_copy ( self.queue, Vgrid, self.Vgrid_buff         )
            return Vgrid
```

**Comment by geggo** [comment]
> Am 18.10.2024 um 20:39 schrieb Prokop ***@***.***>:
> 
> ﻿
> I'm using gpyfft for calculating poisson equation on GPU.
> 
> the algorithm is like this>
> 
> FFT charge density rho(r) to k-space rho(k)
> multiply fequncey component by 1/|k^2| krenel, $$V(k)=rho(k)/|k|^2$$
> inverse-FFT the resulting electrostatic potential V(k) -> V(r)
> But I don't know how to initialize inverse fourier transform,
> 
The enqueue  method of the FFT class takes an forward=False argument to calculate the inverse transform. 
Hope that helps
Gregor
