### ISSUE TITLE
test_simple.py hangs

### ISSUE THREAD

**Issue by cancan101** [geggo/gpyfft#9]
test_simple.py seems to hang on: `queue.finish()`
gpyfft/fft.py runs without an issue.
UPDATE: The hanging is caused by the kernel taking so long that the TDR kills python, etc: http://msdn.microsoft.com/en-us/library/windows/hardware/ff570087(v=vs.85).aspx

**Comment by geggo** [comment]
Reworked resource deallocation, so time to close this issue...
